server:
  port: 7080

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  application:
    name: icrm-server

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://10.0.0.8:7071/.well-known/jwks.json"

# &serverTimezone=UTC
  datasource:
    url: jdbc:mysql://10.0.0.8:3306/olive-stage?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always


  jpa:
    hibernate:    
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect    
      
logging:
  file:
    name: ./logs/icrm-server.log
